### ISSUE TITLE
Add Missionleader Actor to specc

### ISSUE THREAD

**Issue by whije330** [whije330/SEP-g08-usermanual#63]

**Comment by DSLMike** [comment]
- created actLeader and adjusted operations of actOfficer (Login)
- created all datatypes and use cases for use case summary suCompleteMission (with the view)

**Comment by DSLMike** [comment]
- documented every datatype, use case, use case summary and views created of actLeader.

**Comment by DSLMike** [comment]
- generated new report, everything went fine, no errors.
Also uploaded new zip to spec github.
