### ISSUE TITLE
Add a actor which shared operations of actVictim and actWitness

### ISSUE THREAD

**Issue by whije330** [whije330/SEP-g08-usermanual#64]

**Comment by DSLMike** [comment]
Im referring to sending the pictures and indications of what was the ignition of the fire. Those two operations are exactly the same for the victim and witness.

**Comment by DSLMike** [comment]
First test trying to figure out how to do a "superclass", which will then be used by actVictim and actWitness. By "be used", I'm referring to actVitcim and actWitness will inherit two in-/out functions of that "superclass".

**Comment by DSLMike** [comment]
- got it working for most of the use cases, only 2 use case summaries have warnings now.

**Comment by DSLMike** [comment]
After a long debugging time and revoking most changes (used old backup). Got it to work again, with no more errors...
- Added actSmartphoneUser, which is used to be extended by actWitness and actVictim
- Removed all duplicates (use cases, operations)
- Added actSmartphoneUsers' operations and use cases + use case instances.
- Finally documented every use case-instance and views which were already present for the actWitness, actVictim and actSmartphoneUser.

TODO: Create missing usecase views and usecase instance views and document them!

**Comment by DSLMike** [comment]
Done
